### PR TITLE
character creation select boxes file created

### PR DESCRIPTION
**Pull request by Wildlovelies**
Firefox and chrome wont display the selections for me, could be an issue on my end though.

### CODE REVIEW

**Comment by bleehu** [comment]
When you create a PR, go ahead and set the "Awaiting Review" label and assign it to me :)
Do you think we should have the All-characters page and the Character creation page on the same page? Or should they each be a separate page? Not sure what the right answer is.

**Comment by Wildlovelies** [comment]
I think the all characters sheet should be a separate page that just pulls up links to the separate characters. But the all characters list was included with the page the issue listed to start with.

Quick side note, the character notes at the bottom, I have changed the names inside the brackets to correctly reflect the names of the items above, I wasn't sure if those line items called another page's function's, and changing them could break that.

**Comment by bleehu** [comment]
Keeping track of characters is going to take several pages. For best practices, we're going to want to be able to 
Create characters
Read characters, both having a user read their characters and having admins read characters aggregates.
Update characters, especially leveling up characters
Delete characters when necessary.

Since we can't have one user deleting another's character, we will need each character's owner to not just be the name of the user who created it, but have a link (managed on the backend) to the owner's account.

So there will likely be at least 4 pages;
1) create a new character
2) update a character
2.5) maybe level up a character is a different page?
3) read (with the option to delete) characters that belong to the user
4) Read stats on all characters

**Comment by bleehu** [comment]
@Wildlovelies , go ahead and hit the big green merge button and delete the branch so that we don't have a huge list of unused branches.

**Pull request merged**
