### PR TITLE
Mh/refactor/skills

### PR DESCRIPTION
**Pull request by bleehu**
Still could use some cleaning up, but the feature works now!

### CODE REVIEW

**Comment by RyuGuardian** [comment]
I tried modifying a character to add new skills and it didn't work, but I neither had skill points nor used a real skill name. Not sure how this is supposed to work...

**Comment by bleehu** [comment]
Can you send a stack trace of the error? What py file does it say that it's coming from? 
These issues should be addressed in this PR before merge.

**Comment by RyuGuardian** [comment]
Both are in character_routes.py:
```
Traceback (most recent call last):
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/projects/CXDocs/server/characters/character_routes.py", line 119, in char_select
    character_blob = character.get_characters()
NameError: global name 'character' is not defined
```
```
Traceback (most recent call last):
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/projects/CXDocs/server/characters/character_routes.py", line 89, in update_character
    new_character = characters.validate_character(request.form, user_id)
NameError: global name 'user_id' is not defined
```

**Comment by bleehu** [comment]
uhh... what? In your second error, line 89 isn't `new_character = characters.validate_character(request.form, user_id)` anymore. Did you pull?

**Comment by RyuGuardian** [comment]
Lines up for me, and if I check the file on this PR's latest commit. Are you on the right branch?

**Comment by bleehu** [comment]
nope, you're right, my bad. Hang on.

**Comment by bleehu** [comment]
@RyuGuardian how'zat?

**Comment by RyuGuardian** [comment]
I got another error when hitting "Select Character." I'm going to send you a screenshot on Slack.

**Comment by bleehu** [comment]
Let's roll these changes into the refactor that I'm doing in MH/airplain/refactor; I've got some changes that write over this anyway. I'll also pull in your nav branch. If we're gonna do monolithic changes, why not to one huge monolithic change? It'll be... great...?

**Comment by bleehu** [comment]
Ya, character selection has been broken for quite a while. I think we deprecate it and re-build it when we have more searchable and dynamic pages. Mind if I yank it in a subsqeuent PR?

**Comment by RyuGuardian** [comment]
Already approved that. Would it be better to close this and create a new PR when you're done with the other stuff?

**Comment by bleehu** [comment]
Or we could update this PR with that new work using the git merge command? How's that look now?

**Comment by RyuGuardian** [comment]
I guess since Select Character is gone, this can be approved now. Not running into any other problems related to this.

**Pull request merged**
