### PR TITLE
Turtlelord26 HowTo docs

### PR DESCRIPTION
**Pull request by Turtlelord26**
Addressing multiple Issues, see individual commit descriptions.

Intending to use this as a superbranch for further HowTo document submissions.

### CODE REVIEW

**Comment by Turtlelord26** [comment]
@bleehu I can't find how you attached the URL https://54.200.202.155/monsterweaponshowto to the weapons howto page so it's entirely possible the new pages don't have the correct addresses in the links I put in index. Help please.

**Comment by bleehu** [comment]
To wire up a page to a URL, we add an `@app.route` statement in start.py. The documentation for it is here: http://flask.pocoo.org/docs/0.12/quickstart/#a-minimal-application but I can totally handle adding the routes this time if you'd like.

**Comment by bleehu** [comment]
I'd like to hold off on merging this until both
 [ ] We've added content to the places that say `<p> text </p>`
 [ ] and I've added the links correctly

**Comment by Turtlelord26** [comment]
It strikes me that if my intent was to collect work toward this goal on github but not merge it until some point in the future when it had more content, I should have made the branch but not the PR.

**Comment by bleehu** [comment]
probably. But not a big deal :)

**Pull request merged**
